### ISSUE TITLE
validation error display_name

### ISSUE THREAD

**Issue by MarcoMadera** [MarcoMadera/Rindu#273]
**Describe the bug**
500 errors in server fetching this is playlist, as "this is" playlist are a pure search of artirst it may contain any playlist, and the owner can be invalid causing this error:

```
TypeError: Cannot read properties of null (reading 'display_name')
    at /var/task/.next/server/pages/dashboard.js:1:19712
    at Array.filter (<anonymous>)
    at /var/task/.next/server/pages/dashboard.js:1:19673
    at Array.forEach (<anonymous>)
    at K (/var/task/.next/server/pages/dashboard.js:1:19450)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  page: '/dashboard'
}
```

**To Reproduce**
To investigate

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Product: [e.g. premium, open]
- Page: [e.g. /dashboard, playlist/{id}]

**Comment by MarcoMadera** [comment]
This was fixed in #384 https://github.com/MarcoMadera/Rindu/commit/6564c4905ed6a40820f718e3eaffd9e93ed07af6#diff-d5c80dff585b076e372b7c7ab3bc89f4597c5b9550fab612e0973aced040d59bR577
