### ISSUE TITLE
Progress Bar action click not working after a track has been played.

### ISSUE THREAD

**Issue by MarcoMadera** [MarcoMadera/Rindu#312]
**Describe the bug**

**To Reproduce**
1. Plays some music with a track in queue or a playlist
2. Wait until the song ends, and next track is playing.
3. Try to click in any time the progress bar and listen the music is not changing.
4. See auto play failed error

**Expected behavior**
I should be able to seek any time in music while playing.

**Screenshots**
<img width="1259" alt="image" src="https://github.com/MarcoMadera/Rindu/assets/17222523/dbadd35b-9434-46e8-b0dd-539959fc1bf2">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Product: [e.g. premium, open]
- Page: [e.g. /dashboard, playlist/{id}]

**Comment by MarcoMadera** [comment]
```
Seems an issue with spotify sdk:

index.js:3  Uncaught (in promise) PlaybackError: The operation is not allowed.
at new t (index.js:3:339908)
at t.seek (index.js:3:364509)
at t._handleSeekCommand (index.js:33:34221)
at t._performCommand (index.js:33:33899)
at t._onMessage (index.js:33:25367)
at e.n (index.js:18:74588)
at e._dispatchFromStore (index.js:18:10052)
at Array.<anonymous> (index.js:18:11653)
at o (index.js:18:7851)
at r (index.js:18:8295)
```

[disallow_seeking_reasons](https://developer.spotify.com/documentation/commercial-hardware/implementation/reference/latest#:~:text=uint32_t-,disallow_seeking_reasons,-Bitfield%20of%20reasons) 

Playback state returning
`restrictions.disallow_seeking_reasons = "unknown_reason"`

**Comment by MarcoMadera** [comment]
Closing as it was fixed in the new version
